# Generated by Django 4.2.17 on 2025-02-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='top_rated',
            field=models.BooleanField(default=False),
        ),
    ]
