# Generated by Django 4.2.17 on 2025-03-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_top_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='read_duration',
            field=models.IntegerField(default=10),
        ),
    ]
