# Generated by Django 4.2.17 on 2025-03-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_read_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='read_duration',
            field=models.IntegerField(default=10, help_text='Enter the read duration in minutes'),
        ),
    ]
