# Generated by Django 4.2.17 on 2024-12-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('business_name', models.CharField(max_length=200)),
                ('requested_service', models.CharField(choices=[('business_plan_financial_projection', 'Business Plan + Financial Projection'), ('business_plan_financial_model_pitch_deck', 'Business Plan + Financial Model (Cap Valuation) + Pitch Deck'), ('pitch_deck', 'Pitch Deck'), ('company_profile', 'Company Profile'), ('desktop_market_research', 'Desktop Market Research'), ('primary_market_research', 'Primary Market Research'), ('recruitment', 'Recruitment (We charge lesser than other firms)'), ('talent_management', 'Talent Management'), ('business_proposal', 'Business Proposal'), ('feasibility_study_report', 'Feasibility Study Report'), ('operational_setup', 'Operational Setup'), ('financial_model_alone', 'Financial Model alone'), ('business_training', 'Business Training for Executives/Team Members'), ('business_advisory', 'Business Advisory'), ('others', 'Others (Specify in the Subject)')], max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('country', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('job_description', models.TextField()),
                ('qualification', models.TextField()),
                ('duties', models.TextField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('contract_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], max_length=20)),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TalenttaFormEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('professional_skills', models.TextField()),
                ('talentta_expectation', models.TextField()),
            ],
        ),
    ]
