# Generated by Django 4.2.17 on 2024-12-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobopening',
            name='closed',
        ),
        migrations.AddField(
            model_name='jobopening',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
