# Generated by Django 4.2.17 on 2025-02-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('funding', 'Funding & Investor'), ('additional', 'Additional Questions')], default='general', max_length=20),
        ),
    ]
