# Generated by Django 4.2.17 on 2025-03-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_features_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
