# Generated by Django 4.2.17 on 2025-03-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_pricing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
