# Generated by Django 4.2.17 on 2025-04-01 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_pricing_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talenttaformentry',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterField(
            model_name='contacts',
            name='requested_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.features'),
        ),
    ]
