# Generated by Django 4.2.17 on 2025-04-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_talenttaformentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'Service (Pricing Feature)', 'verbose_name_plural': 'Services (Pricing Features)'},
        ),
        migrations.AlterModelOptions(
            name='pricing',
            options={'verbose_name': 'Pricing', 'verbose_name_plural': 'Pricing Plans'},
        ),
    ]
